/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionSessionIdTerminalRouteImport } from './routes/session.$sessionId.terminal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdTerminalRoute =
  SessionSessionIdTerminalRouteImport.update({
    id: '/session/$sessionId/terminal',
    path: '/session/$sessionId/terminal',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/session/$sessionId/terminal': typeof SessionSessionIdTerminalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/session/$sessionId/terminal': typeof SessionSessionIdTerminalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/session/$sessionId/terminal': typeof SessionSessionIdTerminalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/session/$sessionId/terminal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/session/$sessionId/terminal'
  id: '__root__' | '/' | '/session/$sessionId/terminal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionSessionIdTerminalRoute: typeof SessionSessionIdTerminalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId/terminal': {
      id: '/session/$sessionId/terminal'
      path: '/session/$sessionId/terminal'
      fullPath: '/session/$sessionId/terminal'
      preLoaderRoute: typeof SessionSessionIdTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionSessionIdTerminalRoute: SessionSessionIdTerminalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
